// let str =
//   "this statement is going to use for learning the string methods through out the session";
// console.log(str.length);
// console.log(str.indexOf("statement"));
// console.log(str.indexOf("is"));
// console.log(str.lastIndexOf("going"));
// console.log(str.search("use"));
// let substr = str.slice(27, 45);
// console.log(substr);
// console.log(str.replace("the", "a"));
// let str1 = "Apple-Mango-Orange-Banana";
// console.log(typeof str1);
// let arr = str1.split("-", 2);
// console.log(arr);
// console.log(typeof arr);
// let str2 = "Spiderman";
// console.log(str2.toLowerCase());
// console.log(str2.charAt(4));
// const cities = ["hyderabad", "banglore", "mumbai"];
// const arr_cities = ["delhi", "surat"];
// const new_cities = cities.concat(arr_cities);
// console.log(new_cities);
// console.log(cities);
// console.log(cities[3]);
// console.log(cities[cities.length - 1]);
// cities.push("srinagar");
// console.log(cities);
// cities.unshift("chennai");
// console.log(cities);
// cities.pop();
// console.log(cities);
// cities.shift();
// console.log(cities);
// cities.splice(1, "chennai", "banglore");
// console.log(cities);
// let new_str = cities.join();
// console.log(new_str);
// console.log(typeof new_str);
